language: python
dist: trusty
sudo: false
cache: pip

python:
  - '3.6'
  - '3.7-dev'
  - 'nightly'

matrix:
  allow_failures:
    - python: nightly
  fast_finish: true

install:
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint --reports=yes mallard

notifications:
  email:
    on_success: change
    on_failure: always
